image: maven:3.9.6-eclipse-temurin-21

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "-s .m2/settings.xml -DskipTests"

cache:
  paths:
    - .m2/repository/

stages:
  - build
  - release

build:
  stage: build
  script:
    - mvn clean package
    - export RELEASE_VERSION=$(mvn --non-recursive help:evaluate -Dexpression=project.version -q -DforceStdout)
    - export ARTIFACT_ID=$(mvn --non-recursive help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
    - export JAR_FILE=$(ls target/${ARTIFACT_ID}.jar)
    - echo "RELEASE_VERSION=$RELEASE_VERSION" >> release.env
    - echo "ARTIFACT_ID=$ARTIFACT_ID" >> release.env
    - echo "JAR_FILE=$JAR_FILE" >> release.env
    - echo "Built JAR $JAR_FILE"
    - echo "RELEASE_VERSION = $RELEASE_VERSION"
    - awk '/^## \[Unreleased\]/{flag=1; next} /^## \[/{if(flag) exit} flag' CHANGELOG.md > release-notes.md
    - |
      curl --fail --header "JOB-TOKEN: $CI_JOB_TOKEN" \
           --header "Content-Type: application/java-archive" \
           --upload-file $JAR_FILE \
           "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/$ARTIFACT_ID/v$RELEASE_VERSION/$ARTIFACT_ID.jar"
  artifacts:
    reports:
      dotenv: release.env
    paths:
      - release-notes.md
    expire_in: 1 week
  only:
    - main

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: build
      artifacts: true
  script:
    - echo "Creating release v$RELEASE_VERSION"
  release:
    name: "Release v$RELEASE_VERSION"
    description: "./release-notes.md"
    tag_name: "v$RELEASE_VERSION"
    assets:
      links:
        - name: "$ARTIFACT_ID.jar"
          url: "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/$ARTIFACT_ID/v$RELEASE_VERSION/$ARTIFACT_ID.jar"
          link_type: package
  only:
    - main
  when: on_success
